/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppActivityRouteImport } from './routes/app/activity'
import { Route as AppChallengesRouteImport } from './routes/app/challenges'
import { Route as AppCirclesRouteImport } from './routes/app/circles'
import { Route as AppDiscoverRouteImport } from './routes/app/discover'
import { Route as AppHelpRouteImport } from './routes/app/help'
import { Route as AppInboxRouteImport } from './routes/app/inbox'
import { Route as AppPlusRouteImport } from './routes/app/plus'
import { Route as AppPostRouteImport } from './routes/app/post'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppSafetyRouteImport } from './routes/app/safety'
import { Route as AppSearchRouteImport } from './routes/app/search'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppWalletRouteImport } from './routes/app/wallet'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppChatIdRouteImport } from './routes/app/chat.$id'
import { Route as AppFavorIdRouteImport } from './routes/app/favor.$id'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile.index'
import { Route as AppProfileIdRouteImport } from './routes/app/profile.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesRoute = AppChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesRoute = AppCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppPlusRoute = AppPlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => AppRoute,
} as any)
const AppPostRoute = AppPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSafetyRoute = AppSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFavorIdRoute = AppFavorIdRouteImport.update({
  id: '/favor/$id',
  path: '/favor/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/challenges': typeof AppChallengesRoute
  '/app/circles': typeof AppCirclesRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/help': typeof AppHelpRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/plus': typeof AppPlusRoute
  '/app/post': typeof AppPostRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/safety': typeof AppSafetyRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/favor/$id': typeof AppFavorIdRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/app/profile/': typeof AppProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/challenges': typeof AppChallengesRoute
  '/app/circles': typeof AppCirclesRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/help': typeof AppHelpRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/plus': typeof AppPlusRoute
  '/app/post': typeof AppPostRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wallet': typeof AppWalletRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/favor/$id': typeof AppFavorIdRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/app/profile': typeof AppProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset': typeof ResetRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/challenges': typeof AppChallengesRoute
  '/app/circles': typeof AppCirclesRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/help': typeof AppHelpRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/plus': typeof AppPlusRoute
  '/app/post': typeof AppPostRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/safety': typeof AppSafetyRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/favor/$id': typeof AppFavorIdRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/app/profile/': typeof AppProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot'
    | '/login'
    | '/onboarding'
    | '/reset'
    | '/signup'
    | '/app/activity'
    | '/app/challenges'
    | '/app/circles'
    | '/app/discover'
    | '/app/help'
    | '/app/inbox'
    | '/app/plus'
    | '/app/post'
    | '/app/profile'
    | '/app/safety'
    | '/app/search'
    | '/app/settings'
    | '/app/wallet'
    | '/app/'
    | '/api/auth/$'
    | '/app/chat/$id'
    | '/app/favor/$id'
    | '/app/profile/$id'
    | '/app/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/login'
    | '/onboarding'
    | '/reset'
    | '/signup'
    | '/app/activity'
    | '/app/challenges'
    | '/app/circles'
    | '/app/discover'
    | '/app/help'
    | '/app/inbox'
    | '/app/plus'
    | '/app/post'
    | '/app/safety'
    | '/app/search'
    | '/app/settings'
    | '/app/wallet'
    | '/app'
    | '/api/auth/$'
    | '/app/chat/$id'
    | '/app/favor/$id'
    | '/app/profile/$id'
    | '/app/profile'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot'
    | '/login'
    | '/onboarding'
    | '/reset'
    | '/signup'
    | '/app/activity'
    | '/app/challenges'
    | '/app/circles'
    | '/app/discover'
    | '/app/help'
    | '/app/inbox'
    | '/app/plus'
    | '/app/post'
    | '/app/profile'
    | '/app/safety'
    | '/app/search'
    | '/app/settings'
    | '/app/wallet'
    | '/app/'
    | '/api/auth/$'
    | '/app/chat/$id'
    | '/app/favor/$id'
    | '/app/profile/$id'
    | '/app/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetRoute: typeof ResetRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/challenges': {
      id: '/app/challenges'
      path: '/challenges'
      fullPath: '/app/challenges'
      preLoaderRoute: typeof AppChallengesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/circles': {
      id: '/app/circles'
      path: '/circles'
      fullPath: '/app/circles'
      preLoaderRoute: typeof AppCirclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plus': {
      id: '/app/plus'
      path: '/plus'
      fullPath: '/app/plus'
      preLoaderRoute: typeof AppPlusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/post': {
      id: '/app/post'
      path: '/post'
      fullPath: '/app/post'
      preLoaderRoute: typeof AppPostRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/safety': {
      id: '/app/safety'
      path: '/safety'
      fullPath: '/app/safety'
      preLoaderRoute: typeof AppSafetyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chat/$id': {
      id: '/app/chat/$id'
      path: '/chat/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favor/$id': {
      id: '/app/favor/$id'
      path: '/favor/$id'
      fullPath: '/app/favor/$id'
      preLoaderRoute: typeof AppFavorIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/app/profile/$id': {
      id: '/app/profile/$id'
      path: '/$id'
      fullPath: '/app/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppProfileRoute
    }
  }
}

interface AppProfileRouteChildren {
  AppProfileIdRoute: typeof AppProfileIdRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileIdRoute: AppProfileIdRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppChallengesRoute: typeof AppChallengesRoute
  AppCirclesRoute: typeof AppCirclesRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppHelpRoute: typeof AppHelpRoute
  AppInboxRoute: typeof AppInboxRoute
  AppPlusRoute: typeof AppPlusRoute
  AppPostRoute: typeof AppPostRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppSafetyRoute: typeof AppSafetyRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatIdRoute: typeof AppChatIdRoute
  AppFavorIdRoute: typeof AppFavorIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppChallengesRoute: AppChallengesRoute,
  AppCirclesRoute: AppCirclesRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppHelpRoute: AppHelpRoute,
  AppInboxRoute: AppInboxRoute,
  AppPlusRoute: AppPlusRoute,
  AppPostRoute: AppPostRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppSafetyRoute: AppSafetyRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatIdRoute: AppChatIdRoute,
  AppFavorIdRoute: AppFavorIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetRoute: ResetRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
